version: '3.9'
services:
  mysql:
    image: 'mysql:5.7'
    env_file: .env
    working_dir: /application
    volumes:
      - bancos_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=300M --sql_mode=
    networks:
      - rede_erp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MAX_EXECUTION_TIME: 9999
      UPLOAD_LIMIT: 30000000000
    networks:
      - rede_erp

  webserver:
    #carrega as informações do Dockerfile
    build: .
    ports:
      - '8000:80'
    restart: always
    networks:
      - rede_erp

networks:
  rede_erp:
    driver: bridge

volumes:
  bancos_mysql:
    external: true